### ISSUE TITLE
GPIO25 (LED) works, all others GPIOs don't

### ISSUE THREAD

**Issue by b-ferd** [notro/pico-usb-io-board#5]
Got the project working on the Rpi Pico, with Ubuntu Kernel 6.2.0-39.
For now I'm accessing the GPIOs using gpioset. This works for the green onboard LED:
$ gpioset dln2 25=1
$ gpioset dln2 25=0
but does not do anything for the other GPIO pins.
They do get set to "Output" automatically when writing to them, as _gpioinfo_ shows, but they do not go high (measured with Multimeter).
Attaching an LED via 330R to GND, I can very briefly see the LED flash when setting the GPIO pin to high - but that's it.
Any suggestions or ideas what might go wrong here?

**Comment by notro** [comment]
Try ```gpioset --mode=signal```. See [man page](https://manpages.debian.org/experimental/gpiod/gpioset.1.en.html#Modes:) for more info.

GP25 is treated differently from the others as mentioned here: https://github.com/notro/pico-usb-io-board/wiki#gpio

**Comment by b-ferd** [comment]
Ahh, classical Layer-8-issue...
Thanks for the clarification! was aware that GP25 is treated differently with regards of allocation as I/O, but not that it behaves differently with regards to acting "sticky" when setting it to high/low (had skimmed through the code as well, but nothing caught my eye immediately).
Might be be something to add to the docu still that this IO not only is allocated as output permanently, but that it also behaves a bit differently than the others.
